name: Changeset Bot
env:
  BOT_TOKEN: ${{ secrets.CHANGESET_BOT }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  changeset-check:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      - name: Run Changeset Checker
        run: |
          yarn add -W @octokit/rest
          node packages/manager/scripts/changelog/changeset-bot.mjs