name: Changeset Bot Receive PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  changeset-bot:
    runs-on: ubuntu-latest
    name: Changeset Bot

    steps:
      - uses: actions/checkout@v3

      # imitation of a build process
      - name: Build
        run: /bin/bash ./build.sh

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/

      - name: Run Changeset Checker
        uses: ./packages/manager/scripts/changelog
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
