name: Code Coverage

on: [pull_request]

jobs:
  base_branch:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         ref: ${{ github.base_ref }} # The base branch of the PR (develop)

      - name: Use Node.js v18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      - name: Install Dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: Run Base Branch Coverage
        run: yarn coverage:summary

      - name: Write Base Coverage to an Artifact
        run: |
          coverage_json=$(cat ./packages/manager/coverage/coverage-summary.json)
          pct=$(echo "$coverage_json" | jq -r '.total.lines.pct | sprintf("%.2f", .)')
          echo "$pct" > ref_code_coverage.txt

      - name: Upload Base Coverage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ref_code_coverage
          path: ref_code_coverage.txt

  current_branch:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: base_branch

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      - name: Install Dependencies
        run: yarn

      - name: Run Build
        run: yarn build

      - name: Run Current Branch Coverage
        run: yarn coverage:summary

      - name: Write PR Number to an Artifact
        run: |
          echo "${{ github.event.number }}" > pr_number.txt

      - name: Write Current Coverage to an Artifact
        run: |
          coverage_json=$(cat ./packages/manager/coverage/coverage-summary.json)
          pct=$(echo "$coverage_json" | jq -r '.total.lines.pct | sprintf("%.2f", .)')
          echo "$pct" > current_code_coverage.txt

      - name: Upload PR Number Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr_number.txt

      - name: Upload Current Coverage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: current_code_coverage
          path: current_code_coverage.txt
