name: Code Coverage Summary Report

on: [pull_request]

jobs:
  code_coverage_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.base_ref }} # The base branch of the PR (develop)
      - name: Use Node.js v18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      - name: Install dependencies
        run: yarn

      - name: Run test coverage
        run: yarn workspace linode-manager run test