name: Code Coverage

on: [pull_request]

jobs:
  base_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }} # The base branch of the PR (develop)
      
      - name: Use Node.js v18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      - name: Install dependencies
        run: yarn

      - name: Run base branch coverage and write to a file
        # Uncomment when ready to run
        # run: |
        #   raw_coverage_output=$(yarn coverage:get)
        #   ref_coverage_value==$(echo "$raw_coverage_output" | awk '/^[0-9]+\.[0-9]+$/{print; exit}')
        #   echo "$ref_coverage_value" > ref_code_coverage.txt
        run: |
          echo "65" > ref_code_coverage.txt
      
      - name: Upload code coverage for base branch
        uses: actions/upload-artifact@v3
        with:
          name: ref_code_coverage
          path: ref_code_coverage.txt

  current_branch:
    runs-on: ubuntu-latest
    needs: base_branch

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"
      
      - name: Download code coverage report from base branch
        uses: actions/download-artifact@v3
        with:
          name: ref_code_coverage

      - name: Install dependencies
        run: yarn

      - name: Yarn test with coverage
        run: yarn workspace linode-manager run test:ci

      - name: Run current branch coverage and write to a file
        run: |
          raw_coverage_output=$(yarn coverage:get)
          current_coverage_value=$(echo "$raw_coverage_output" | awk '/^[0-9]+\.[0-9]+$/{print; exit}')
          echo "$current_coverage_value" > current_code_coverage.txt
      
      - name: Generate Comment with Code Coverage
        run: |
          base_coverage=$(cat ref_code_coverage.txt)
          current_coverage=$(cat current_code_coverage.txt)
          if (( $(echo "$current_coverage < $base_coverage" | bc -l) )); then
            icon="❌" # Error icon
          else
            icon="✅" # Check mark icon
          fi
          comment_message="$icon Coverage Report\nBase Coverage: $base_coverage\nCurrent Coverage: $current_coverage"
          echo "Coverage: $comment_message"
          echo "$comment_message" > updated_comment.txt

      - name: Update Coverage Badge
        run: yarn coverage:update

      - name: Check Coverage
        run: |
          if (( $(echo "$current_coverage < $base_coverage" | bc -l) )); then
            echo "Error: Current coverage is lower than base coverage"
            exit 1 # Fail the check
          fi

      - name: Post Comment
        uses: mshick/add-pr-comment@v2
        with:
          proxy-url: https://serviceapp.cloud
          message: |
            <strong>Coverage Report</strong>:\n
            $(cat updated_comment.txt)

