name: Coverage Comment

on:
  workflow_run:
    workflows: ["Code Coverage"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # TODO: Uncomment the following lines to enable coverage comment in part 2
      # It should work in theory, but want to limit the noise in everyone's PRs for now until
      # I can confirm the action works as expected
      - name: Download base coverage artifact
        uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e #v2.28.0
        with:
          workflow: "coverage.yml"
          run_id: ${{ github.event.workflow_run.id }}
          name: ref_code_coverage

      - name: Download current coverage artifact
        uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e #v2.28.0
        with:
          workflow: "coverage.yml"
          run_id: ${{ github.event.workflow_run.id }}
          name: current_code_coverage

      - name: Update Coverage Badge
        run: yarn coverage:badge

      - name: Generate Coverage Comment
        run: |
          base_coverage=$(cat ref_code_coverage.txt)
          current_coverage=$(cat current_code_coverage.txt)
          if (( $(echo "$current_coverage < $base_coverage" | bc -l) )); then
            icon="❌" # Error icon
          else
            icon="✅" # Check mark icon
          fi
          comment_message="**Coverage Report:** $icon<br>Base Coverage: $base_coverage%<br>Current Coverage: $current_coverage%"
          echo "Coverage: $comment_message"
          echo "$comment_message" > updated_comment.txt

      - name: Post Comment
        uses: mshick/add-pr-comment@7c0890544fb33b0bdd2e59467fbacb62e028a096 #v2.8.1
        with:
          message: |
            $(cat updated_comment.txt)

      - name: Validate Coverage
        run: |
          base_coverage=$(cat ref_code_coverage.txt)
          current_coverage=$(cat current_code_coverage.txt)
          if (( $(echo "$current_coverage < $base_coverage" | bc -l) )); then
            echo "Error: Current coverage is lower than base coverage"
            exit 1 # Fail the check
          fi
