name: Code Coverage

on: [pull_request]

jobs:
  base_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # TODO: Remove this comment after merging to develop
        # with:
        #  ref: ${{ github.base_ref }} # The base branch of the PR (develop)

      - name: Use Node.js v18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: Run base branch coverage
        run: yarn coverage:summary

      - name: Write base coverage to an artifact
        run: |
          coverage_json=$(cat ./packages/manager/coverage/coverage-summary.json)
          pct=$(echo "$coverage_json" | jq -r '.total.lines.pct')
          echo "$pct" > ref_code_coverage.txt

      - name: Upload base coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: ref_code_coverage
          path: ref_code_coverage.txt

  current_branch:
    runs-on: ubuntu-latest
    needs: base_branch

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: Run current branch coverage
        run: yarn coverage:summary

      - name: Write current coverage to an artifact
        run: |
          coverage_json=$(cat ./packages/manager/coverage/coverage-summary.json)
          pct=$(echo "$coverage_json" | jq -r '.total.lines.pct')
          echo "$pct" > current_code_coverage.txt

      - name: Upload current coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: current_code_coverage
          path: current_code_coverage.txt

