name: Coverage Badge

on:
  push:
    branches:
      - develop
      - staging
      - master

jobs:
  generate-coverage-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js v18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      - name: Install Dependencies
        run: yarn

      - name: Run Build
        run: yarn build

      - name: Run Base Branch Coverage
        run: yarn coverage:summary

      - name: Generate Coverage Badge
        uses: jaywcjlove/coverage-badges-cli@7f0781807ef3e7aba97a145beca881d36451b7b7 # v1.1.1
        with:
          label: '@linode/manager coverage'
          source: ./packages/manager/coverage/coverage-summary.json
          output: ./packages/manager/coverage/badges.svg
