name: Code Coverage Summary Report

on: [pull_request]

jobs:
  code_coverage_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.base_ref }} # The base branch of the PR (develop)
      - name: Use Node.js v18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.14"

      - name: Install dependencies
        run: yarn

      - name: Run test coverage
        run: yarn workspace linode-manager run test

      # - name: Upload code coverage for ref branch
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: base-lcov
      #     path: packages/manager/coverage/lcov.info

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: packages/manager/coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '40 80'
      
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md